### ISSUE TITLE
Crash: category editor

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1378] opened 2017-12-03 19:24 UTC
From: 
 Details:
os: 1-10-13
vs: 1-10-0-8
/Applications/GeoDa.app/Contents/MacOS/../Resources/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Entering ConnectDatasourceDlg::SaveRecentDataSource
Exiting ConnectDatasourceDlg::SaveRecentDataSource
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:

Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In GdaFrame::OnUniqueValues()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
SAN2004
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
In TableFrame::OnActivate
In GdaFrame::OnNewCustomCatClassifA()
MapCanvas::NewCustomCatClassif()
Open CatClassifFrame
In CatClassifPanel::PromptNew
suggested title:
field name:SAN2004
MapCanvas::CreateAndUpdateCategories()

**Comment by jkoschinsky** [comment] 2018-01-31 16:53
try to get a crash involving the category editor (e.g. create new category and use it in map and other views)

**Comment by YidanJ-Wu** [comment] 2018-02-02 04:44
Windows 8 
GeoDa 1.12.1.85
Not a crash but the histogram displays one of the intervals as disproportionately large: 
![image](https://user-images.githubusercontent.com/22801047/35716865-30438eac-07a1-11e8-826c-44ab619799a7.png)
Map view seems fine:
![image](https://user-images.githubusercontent.com/22801047/35716898-589ad43c-07a1-11e8-83bc-ec2c52c075bd.png)

**Comment by jkoschinsky** [comment] 2018-02-05 23:06
@YidanJ-Wu: could you share the data with Xun so he can replicate?
@lixun910: could you check why that one quantile category is wider than the others when all bins have 17 or 18 records in them?

**Comment by lixun910** [comment] 2018-02-05 23:43
I think this is correct given the intervals/breaks: 12500, 17693.7, 30957.2, 51651.3, 834231.0

**Comment by jkoschinsky** [comment] 2018-02-06 00:03
something still doesn't quite look right with the category editor:
e.g. with 1.12.1.87 and Guerry data

Steps: 
1. create quantile breaks, 5 cateogies, litercy
2. apply to histogram
-->breaks are the same but # of records in bins seem to differ (see below)
3. save categories and create histogram
--> gives 7 categories (see below)

<img width="1556" alt="screen shot 2018-02-05 at 5 57 21 pm" src="https://user-images.githubusercontent.com/13679743/35835177-de39f992-0a9e-11e8-8174-265e268abb9a.png">

**Comment by YidanJ-Wu** [comment] 2018-02-07 00:48
@lixun910 I used the ohlung file from this gdb 
[ohlung.gdb.zip](https://github.com/GeoDaCenter/geoda/files/1701311/ohlung.gdb.zip)

Still getting the oddly shaped histogram in 1.12.1.87
![image](https://user-images.githubusercontent.com/22801047/35892272-4b806ae8-0b6e-11e8-9664-336a2ea95a8f.png)

**Comment by lixun910** [comment] 2018-02-10 01:51
@jkoschinsky this should be fixed in latest 93
@YidanJ-Wu I think this is also correct since it's a quantile break and most obs has values in range[2,4]

**Comment by YidanJ-Wu** [comment] 2018-02-12 22:52
Windows 8 
1.12.1.93
Looks fine in latest version. I did notice that the user is allowed to create duplicate breaks. screenshot below shows an example where Break 1 and Break 2 are both 1.0000. 
![image](https://user-images.githubusercontent.com/22801047/36124230-eb6c9752-1014-11e8-81ac-1738f8b58645.png)

**Comment by lixun910** [comment] 2018-03-06 19:06
This is correct. See the distribution of the raw values.
<img width="962" alt="screen shot 2018-03-06 at 12 06 14 pm" src="https://user-images.githubusercontent.com/2423887/37052546-cd274dea-2136-11e8-8421-355eb8924790.png">

**Comment by jkoschinsky** [comment] 2018-03-06 21:23
don't allow the same threshold value for two breaks (see 1 for break 1 and 2 in Julie's screenshot, which generates a stacked bar for 1-1.5).

**Comment by lixun910** [comment] 2018-03-16 02:23
This is not a bug. Please note that the quantile method could create breaks with same values, if the category number is too large and the values are not distributed properly. For example:
Values [0,0,0,0,5,7,9] 5 quantiles: breaks [0, 0, 3, 6.6]  
values [0,5,7,9] 5 quantile: breaks[3.0, 5.4, 6.6, 7.8]

The first case will have two same breaks [0,0], which is the issue in this thread.
I added code to detect this case and prompt an error message "**Breaks with same values were created. Please choose a smaller categories**." Let me know what do you think.

Thanks!

**Comment by lanselin** [comment] 2018-03-16 02:25
Please do not change the interface! This is a user issue. The workbook describes what should be done.

**Comment by lixun910** [comment] 2018-03-16 05:15
Ok got it

**Comment by jkoschinsky** [comment] 2018-03-19 21:06
Fix confirmed in GeoDa v113
OSX

not fixed yet:
don't allow the same threshold value for two breaks:

<img width="1031" alt="screen shot 2018-03-19 at 4 05 14 pm" src="https://user-images.githubusercontent.com/13679743/37622358-6db03198-2b8f-11e8-993b-21fa99dd52e6.png">

**Comment by lixun910** [comment] 2018-03-23 05:23
please see  luc's note: "Please do not change the interface! This is a user issue. The workbook describes what should be done."

my notes:

This is not a bug. Please note that the quantile method could create breaks with same values, if the category number is too large and the values are not distributed properly. For example:
Values [0,0,0,0,5,7,9] 5 quantiles: breaks [0, 0, 3, 6.6]
values [0,5,7,9] 5 quantile: breaks[3.0, 5.4, 6.6, 7.8]

The first case will have two same breaks [0,0], which is the issue in this thread.
I added code to detect this case and prompt an error message "Breaks with same values were created. Please choose a smaller categories." Let me know what do you think.

**Closed** 2018-04-05 14:40 UTC
Labels: Module-CategoryEdit, fixed: verify!
