### ISSUE TITLE
Bubble plot:  Adjust bubble size

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#1157] opened 2017-10-06 21:18 UTC
The slider only works if I slide it.  If I click left or right of the slider, the slider moves but the bubble size does not change.

@emochoa 

os: 3-4-4
vs: 1-12-0-0
/usr/local/geoda/web_plugins/logger.txt
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::InitSamplePanel()
Check auto update:
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
In GdaFrame::OnHelpAbout()
In GdaFrame::OnCheckUpdates()
AutoUpdate::CheckUpdate()
AutoUpdate::GetCheckList()
AutoUpdate::ReadUrlContent()
Click GdaFrame::OnNewProject
 GdaFrame::ShowOpenDatasourceDlg()
ConnectDatasourceDlg::OnSample()
Entering Project::Project (new project)
Project::CommonProjectInit()
Entering Project::InitFromOgrLayer
Datasource name:
/usr/local/geoda/web_plugins/samples.sqlite
Project::GetSpatialReference()
Exiting Project::Project
Click GdaFrame::InitWithProject()
Open TableFrame.
Open MapFrame.
MapCanvas::MapCanvas()
MapCanvas::ChangeMapType()
MapCanvas::VarInfoAttributeChange()
MapCanvas::CreateAndUpdateCategories()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2009
Open HistogramFrame.
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In OnHistogramIntervals()
In HistogramFrame::OnHistogramIntervals()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
In HistogramFrame::OnActivate()
Click GdaFrame::OnSaveCanvasImageAs
Entering TemplateFrame::ExportImage
In HistogramFrame::OnActivate()
PNG selected
In HistogramFrame::OnActivate()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In HistogramFrame::OnActivate()
In ReportBugDlg::OnOkClick()
In HistogramFrame::OnActivate()
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2009
Open BoxPlotCanvas.
In GdaFrame::OnHinge30()
In BoxPlotFrame::OnHinge30
In GdaFrame::OnHinge15()
In BoxPlotFrame::OnHinge15
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick
Close BoxPlotCanvas.
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2000
rentpct08
Open ScatterNewPlotFrame.
Click GdaFrame::OnSetDisplayPrecision
AxisLabelPrecisionDlg with precision = 2.
Click GdaFrame::OnSetDisplayPrecision
AxisLabelPrecisionDlg with precision = 1.
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewLinearSmoother()
In GdaFrame::OnEditLowessParams()
In GdaFrame::OnViewLinearSmoother()
In GdaFrame::OnViewLowessSmoother()
In GdaFrame::OnViewRegimesRegression()
In GdaFrame::OnViewRegimesRegression()
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
Open ScatterPlotMatFrame.
In ScatterPlotMatFrame::OnActivate
In GdaFrame::OnEditVariables()
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In GdaFrame::OnViewLowessSmoother()
In ScatterPlotMatFrame::OnViewLowessSmoother()
In ScatterPlotMatFrame::OnActivate
In ScatterPlotMatFrame::OnActivate
In GdaFrame::OnViewLowessSmoother()
In ScatterPlotMatFrame::OnViewLowessSmoother()
In ScatterPlotMatFrame::OnActivate
Open VariableSettingsDlg
Click VariableSettingsDlg::OnOkClick:
kids2000
rentpct08
kids2008
kids2008
Open ScatterNewPlotFrame.
In GdaFrame::OnPercentile()
Open BubbleSizeDlg.
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In BubbleSizeSliderDlg::OnSliderChange()
In GdaFrame::OnReportBug()
Open ReportBugDlg.
In ReportBugDlg::OnOkClick()

**Comment by YidanJ-Wu** [comment] 2017-10-13 02:21
Windows 8 1.12.1.11
Currently the slider moves a fixed interval if I click to the right/left of it. It does not jump to the place I click on. That is by design, right?

**Comment by VeraB620** [comment] 2018-06-30 12:43
OS X El Capitan 10.11.6
GeoDa 1.12.1.137
Slider only moves when I slide it. Slider does not move when clicked to the right/left of it.

**Closed** 2018-07-04 02:08 UTC
Labels: fixed: verify!
