### ISSUE TITLE
Excess Risk Crash

### ISSUE THREAD

**Issue by GeoDaTester** [GeoDaCenter/geoda#869] opened 2017-05-29 18:32 UTC
Details:
os: 2-6-3
vs: 1-8-16-4
Check auto update:
In TableFrame::OnActivate
Open DataViewerAddColDlg.
Error: XRC error: 1052: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1062: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1066: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column CRIME into Table
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnLabelLeftClickEvent()
Open DataViewerDeleteColDlg.
In DataViewerDeleteColDlg::OnChoice()
In DataViewerDeleteColDlg::OnDelete()
CRIME
In TableFrame::OnActivate
Open DataViewerAddColDlg.
Error: XRC error: 1052: vertical alignment flag 'wxALIGN_CENTRE_VERTICAL' has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1062: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1066: horizontal alignment flag 'wxALIGN_CENTER_HORIZONTAL' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditLength()
DataViewerAddColDlg::OnEditDecimals()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
DataViewerAddColDlg::OnEditName()
Entering DataViewerAddColDlg::OnOkClick
Inserting new column CRIME into Table
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnLabelLeftClickEvent()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnCellChanged()
In TableFrame::OnActivate
In TableFrame::OnCellChanged()
In GdaFrame::OpenQuantile(10)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OpenQuantile(5)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OpenQuantile(8)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OnOpenPercentile()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OnOpenStddev()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OnOpenUniqueValues()
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OpenNaturalBreaks(10)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OpenEqualIntervals(10)
Open VariableSettingsDlg
Error: XRC error: 1174: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1181: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Open MapFrame.
In GdaFrame::OnOpenExcessrisk()
Open VariableSettingsDlg
Error: XRC error: 1415: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1424: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1431: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
CRIME
Open MapFrame.
In GdaFrame::OnOpenExcessrisk()
Open VariableSettingsDlg
Error: XRC error: 1415: 'wxEXPAND' is incompatible with horizontal alignment flag ''wxALIGN_CENTRE_HORIZONTAL'' in a vertical box sizer
Error: XRC error: 1424: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Error: XRC error: 1431: horizontal alignment flag 'wxALIGN_LEFT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
CRIME
Province_c
Open MapFrame.
In GdaFrame::OnOpenSpatialRate()
Open VariableSettingsDlg
Error: XRC error: 1121: horizontal alignment flag 'wxALIGN_RIGHT' has no effect inside a horizontal box sizer, remove it and consider inserting a spacer instead
Click VariableSettingsDlg::OnOkClick:
Open MapFrame.

**Comment by lixun910** [comment] 2017-05-29 22:00
Hi Julia, can you verify the version of the GeoDa you use? this shows GeoDa "1-8-16-4", and this spatial rates bug should be fixed in latest version. Thanks!

**Comment by jkoschinsky** [comment] 2017-05-30 01:46
This wasn't my crash but came in from the world :)
Will close since we confirmed  spatial rates now work.

GeoDa 1.8.16.33 — Mac OSX
Verified.

**Closed by jkoschinsky** 2017-05-30 01:46 UTC
Labels: bug, fixed: verify!, Module-Rates
