### ISSUE TITLE
Geoda quit unexpectedly

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#586] opened 2017-01-31 22:50 UTC
After opening geode 1.8.15.21 on a Mac and then selecting GeoDa > Quit GeoDa, the program closes but an error window appears with the message GeoDa quit unexpectedly. This is not critical, but it is not clear why this message would be generated, when the program closed properly.

**Comment by lixun910** [comment] 2017-01-31 22:56
confirmed. 

This will also cause GeoDa can't start again. You need to copy the installer binary again.

Quick check: this is caused by introducing new wx library, and the open file dialog has been rewritten using a frame instead of dialog because of the pop-up menu is disabled.

**Comment by jkoschinsky** [comment] 2017-02-16 03:19
GeoDa 1.8.15.27 — Mac OSX
Confirmed.

**Comment by jkoschinsky** [comment] 2017-02-27 23:39
from Luc:
I haven’t kept track of the issues, so this may be a known one. When I open
GeoDa 31 but do not add any data and then close it, there is an error: GeoDa
closed unexpectedly. It’s not a real problem, since the program was intended
to close, but it shouldn’t happen.

**Comment by YidanJ-Wu** [comment] 2017-03-01 04:35
GeoDa 1.8.15.31
Windows 8
I opened GeoDa, did not add data, then closed Geoda. There was no error message generated.

**Comment by jkoschinsky** [comment] 2017-03-02 00:01
GeoDa 1.8.15.35 — Mac OSX
Confirmed.

**Closed by jkoschinsky** 2017-03-02 00:01 UTC
Labels: bug, fixed: verify!, Milestone-Release1.8
