### ISSUE TITLE
weights manager properties incorrect/incomplete

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1470] opened 2018-01-22 14:38 UTC
Version 1.12.1.81:
weights manager is incomplete
- sparsity and density are given as 0.00 for natregimes rook?
- descriptive statistics are missing
   - number of observations
   - min neighbors, max neighbors
   - mean neighbors, median neighbors
   - % non-zero 
(not clear what difference is between density and sparsity, but we only need
the % non-zero, which is a clearer term to use)

the descriptive statistics should be added to the project file

**Comment by lanselin** [comment] 2018-01-22 14:50
sparsity and density as 0.00

<img width="320" alt="screen shot 2018-01-22 at 8 33 35 am" src="https://user-images.githubusercontent.com/4008351/35226553-4efe72ba-ff51-11e7-9f24-3ac298588575.png">

**Comment by lixun910** [comment] 2018-01-30 21:05
Please also test the GeoDa project file (.gda) when read/write weights meta data

**Comment by luluzhou766** [comment] 2018-03-10 02:02
Window 7
Geoda 1.12.1.109

<img width="880" alt="9 mar 15" src="https://user-images.githubusercontent.com/36253697/37237085-fb1ff684-2406-11e8-84fb-6c16cd9e87ef.PNG">

**Comment by jkoschinsky** [comment] 2018-03-12 00:43
GeoDa v 111
OSX

When you create a rook file and then load it again in the weights manager, type changes from rook to custom and symmetry from symmetric to unknown. You can prevent this by saving to the project file before closing, then it reads correctly from the project file but I presume we want it to read the correct info.

<img width="1065" alt="screen shot 2018-03-11 at 7 38 50 pm" src="https://user-images.githubusercontent.com/13679743/37260703-4947ad44-2564-11e8-8555-e41505c68492.png">

**Comment by lixun910** [comment] 2018-03-12 00:49
This is correct. Since you can’t tell if it’s a rook or queen .. when load
from raw weights file. That’s why we need a gda project file.

**Comment by jkoschinsky** [comment] 2018-03-12 00:51
fix confirmed
GeoDa v 111
OSX

**Closed by jkoschinsky** 2018-03-12 00:51 UTC
Labels: Module-Weights, to be fixed
